### PR TITLE
first version of a check_ function 

### PR DESCRIPTION
**Pull request by EdwinTh**
added 
- check_noNA
- unit tests

adjusted
- step function

### CODE REVIEW

**Comment by topepo** [comment]
I just checked in a bunch of changes to your PR. I made some modifications (I proposed `check_missing` instead of `check_noNA`. There were very few changes to the core of recipes. It passes all of the checks and I updated the documentation. 

Can you sync and re-submit?

**Comment by EdwinTh** [comment]
I am a bit lost in the woods with all the repos now. I can't find where exactly you made these changes. The "Files changed" and the "Commits" only show my additions. I can't find anything in the fork either. Can you point me to where to look?

**Comment by topepo** [comment]
I committed them to the fork [`pr/104`](https://github.com/topepo/recipes/tree/pr/104) fork on the `topepo/recipes` repo. [Here](https://github.com/topepo/recipes/commit/84a371af155288a9547077d5a86955663ce9532f) is a list of the changes. 

[I find that committing to a PR to be confusing as hell. I never know if I should commit straight to your (forked) repo or to the PR on mine.]

**Comment by EdwinTh** [comment]
It is indeed quite a fuss, think we are all set now, but please do check...

**Comment by topepo** [comment]
One more thing and I think we are there: please add a test file for the column check operation.

**Comment by EdwinTh** [comment]
I am learning something new about PRs every day. I did not know that when I pushed to my own github after doing a PR it was added to the PR automatically. Was not aware I already pushed the checkcolumns, it is unfinished indeed (not only tests are lacking).

**Comment by EdwinTh** [comment]
I think we are all set now.

**Comment by topepo** [comment]
That warning is easy to fix so I'll get it. 

Also, I'll merge in another PR after this that will add [a new option called `skip`](https://github.com/topepo/recipes/blob/skips/vignettes/Skipping.Rmd) (just as an fyi). 

Thanks!

**Pull request merged**
