### PR TITLE
Implement `contrasts` for step_dummy()

### PR DESCRIPTION
**Pull request by DavisVaughan**
I saw that you have a `contrasts` argument that does not currently work. Since you use `model.matrix()` under the hood for all of this, I've come up with an alternative way to do one hot encoding as mentioned in #120 by implementing the `contrasts` argument (this replaces the other PR I had open). By implementing it, we can take advantage of the ability to do (from [here](https://stackoverflow.com/questions/4560459/all-levels-of-a-factor-in-a-model-matrix-in-r)):

```
model.matrix(~ Species, iris, 
             contrasts = list(Species = contrasts(iris$Species, contrasts = FALSE)))
```

What follows are a number of examples that show off the implemented argument. The implementation mirrors how it is used in `model.matrix()`.

<details> 

``` r
library(recipes)
data(iris)

iris2 <- iris
iris2$AB <- rep(c("A", "B"), 75)

rec <- recipe(~ Species + AB, data = iris2)

# Default
rec %>%
  step_dummy(Species, AB) %>%
  prep(training = iris2) %>%
  bake(newdata = iris2)
#> # A tibble: 150 x 3
#>    Species_versicolor Species_virginica  AB_B
#>                 <dbl>             <dbl> <dbl>
#>  1                 0.                0.    0.
#>  2                 0.                0.    1.
#>  3                 0.                0.    0.
#>  4                 0.                0.    1.
#>  5                 0.                0.    0.
#>  6                 0.                0.    1.
#>  7                 0.                0.    0.
#>  8                 0.                0.    1.
#>  9                 0.                0.    0.
#> 10                 0.                0.    1.
#> # ... with 140 more rows

# Setting the contrasts option
options(contrasts = c(unordered = "contr.sum", ordered = "contr.poly"))

rec %>%
  step_dummy(Species, AB) %>%
  prep(training = iris2) %>%
  bake(newdata = iris2)
#> # A tibble: 150 x 3
#>    Species_X1 Species_X2 AB_X1
#>         <dbl>      <dbl> <dbl>
#>  1         1.         0.    1.
#>  2         1.         0.   -1.
#>  3         1.         0.    1.
#>  4         1.         0.   -1.
#>  5         1.         0.    1.
#>  6         1.         0.   -1.
#>  7         1.         0.    1.
#>  8         1.         0.   -1.
#>  9         1.         0.    1.
#> 10         1.         0.   -1.
#> # ... with 140 more rows

options(contrasts = c(unordered = "contr.treatment", ordered = "contr.poly"))

# Setting the contrast option through the contrast arugment
rec %>%
  step_dummy(Species, AB, contrast = list(Species = "contr.sum")) %>%
  prep(training = iris2) %>%
  bake(newdata = iris2)
#> # A tibble: 150 x 3
#>    Species_X1 Species_X2  AB_B
#>         <dbl>      <dbl> <dbl>
#>  1         1.         0.    0.
#>  2         1.         0.    1.
#>  3         1.         0.    0.
#>  4         1.         0.    1.
#>  5         1.         0.    0.
#>  6         1.         0.    1.
#>  7         1.         0.    0.
#>  8         1.         0.    1.
#>  9         1.         0.    0.
#> 10         1.         0.    1.
#> # ... with 140 more rows

# Using a numeric matrix - One Hot!
species_contrast <- list(Species = contrasts(iris$Species, contrasts = FALSE))

rec %>%
  step_dummy(Species, AB, contrast = species_contrast) %>%
  prep(training = iris2) %>%
  bake(newdata = iris2)
#> # A tibble: 150 x 4
#>    Species_setosa Species_versicolor Species_virginica  AB_B
#>             <dbl>              <dbl>             <dbl> <dbl>
#>  1             1.                 0.                0.    0.
#>  2             1.                 0.                0.    1.
#>  3             1.                 0.                0.    0.
#>  4             1.                 0.                0.    1.
#>  5             1.                 0.                0.    0.
#>  6             1.                 0.                0.    1.
#>  7             1.                 0.                0.    0.
#>  8             1.                 0.                0.    1.
#>  9             1.                 0.                0.    0.
#> 10             1.                 0.                0.    1.
#> # ... with 140 more rows

# Using a numeric matrix for both
species_AB_contrast <- list(Species = contrasts(iris2$Species,    contrasts = FALSE),
                            AB      = contrasts(factor(iris2$AB), contrasts = FALSE))

rec %>%
  step_dummy(Species, AB, contrast = species_AB_contrast) %>%
  prep(training = iris2) %>%
  bake(newdata = iris2)
#> # A tibble: 150 x 5
#>    Species_setosa Species_versicolor Species_virginica  AB_A  AB_B
#>             <dbl>              <dbl>             <dbl> <dbl> <dbl>
#>  1             1.                 0.                0.    1.    0.
#>  2             1.                 0.                0.    0.    1.
#>  3             1.                 0.                0.    1.    0.
#>  4             1.                 0.                0.    0.    1.
#>  5             1.                 0.                0.    1.    0.
#>  6             1.                 0.                0.    0.    1.
#>  7             1.                 0.                0.    1.    0.
#>  8             1.                 0.                0.    0.    1.
#>  9             1.                 0.                0.    1.    0.
#> 10             1.                 0.                0.    0.    1.
#> # ... with 140 more rows
```

</details>

### CODE REVIEW

**Comment by topepo** [comment]
Finally getting around to looking at this.

I'd like to remove the `contrast` argument from the step, pull from the global option, and apply this to all factors selected by the step. For example:

```r
> library(dplyr)
> data(iris)
> 
> iris2 <- iris
> iris2$AB <- rep(c("A", "B"), 75)
> 
> defaults <- getOption("contrasts")
> 
> use_poly <- defaults
> use_poly["unordered"] <- "contr.poly"
> 
> options(contrasts = use_poly)
> getOption("contrasts")
   unordered      ordered 
"contr.poly" "contr.poly" 
> 
> model.matrix(~ Species + AB, data = iris2,
+              contrasts.arg = getOption("contrasts")) %>%
+   head()
  (Intercept)  Species.L Species.Q       AB.L
1           1 -0.7071068 0.4082483 -0.7071068
2           1 -0.7071068 0.4082483  0.7071068
3           1 -0.7071068 0.4082483 -0.7071068
4           1 -0.7071068 0.4082483  0.7071068
5           1 -0.7071068 0.4082483 -0.7071068
6           1 -0.7071068 0.4082483  0.7071068
> 
> options(contrasts = defaults)
> getOption("contrasts")
        unordered           ordered 
"contr.treatment"      "contr.poly" 
```

If different encodings are desired for different variables, different calls to `step_dummy` can be used. 

There are some weird things that can happen with alternative contrasts and one hot encodings, and that would be documented in [How are categorical predictors handled in recipes?](https://topepo.github.io/recipes/articles/Dummies.html)

**Comment by topepo** [comment]
@DavisVaughan any thoughts on this?

**Comment by DavisVaughan** [comment]
@topepo taking a look this morning, i'll let you details. Quickly, removing `contrasts` as an argument and using the global option sounds good. Also, using `one_hot` as an argument sounds good too.

**Comment by topepo** [comment]
Thanks

**Pull request closed without merging**
